// IT Career Assessment Questions Database
export const questionBank: string[] = [
  "How do you approach debugging complex software issues?",
  "Describe your ideal work environment for maximum productivity.",
  "What attracts you to the field of data analysis?",
  "How do you stay updated with the latest technology trends?",
  "Tell me about a time you had to learn a new programming language quickly.",
  "How do you handle working under tight deadlines?",
  "What's your approach to code reviews and receiving feedback?",
  "How do you prioritize tasks when managing multiple projects?",
  "Describe your experience working in a team versus working independently.",
  "What motivates you to solve technical problems?",
  "How do you approach documentation and knowledge sharing?",
  "Tell me about your experience with agile methodologies.",
  "How do you balance technical debt with new feature development?",
  "What's your approach to testing and quality assurance?",
  "How do you handle disagreements with team members about technical decisions?",
  "Describe a challenging bug you've fixed and how you approached it.",
  "How do you ensure your code is maintainable and scalable?",
  "What's your process for learning new technologies or frameworks?",
  "How do you approach system design and architecture decisions?",
  "Tell me about a time you improved an existing process or system.",
  "How do you manage context switching between different tasks?",
  "What's your approach to mentoring junior developers?",
  "How do you handle production incidents and emergencies?",
  "Describe your experience with continuous integration and deployment.",
  "How do you approach security considerations in your code?",
  "What's your strategy for managing technical complexity?",
  "How do you balance speed of delivery with code quality?",
  "Tell me about your experience with database design and optimization.",
  "How do you approach API design and development?",
  "What's your process for troubleshooting performance issues?",
  "How do you stay focused and productive throughout the workday?",
  "Describe your experience with cloud platforms and services.",
  "How do you approach refactoring legacy code?",
  "What's your philosophy on automated testing versus manual testing?",
  "How do you handle technical disagreements during code reviews?",
  "Tell me about a time you had to make a difficult technical trade-off.",
  "How do you approach learning from mistakes and failures?",
  "What's your strategy for managing work-life balance in tech?",
  "How do you contribute to building a positive team culture?",
  "Describe your experience with version control and branching strategies.",
  "How do you approach estimating time for technical tasks?",
  "What's your process for staying organized with multiple responsibilities?",
  "How do you handle ambiguous requirements or changing specifications?",
  "Tell me about your experience with different development methodologies.",
  "How do you approach technical documentation for end users?",
  "What's your strategy for preventing burnout in demanding projects?",
  "How do you approach collaborating with non-technical stakeholders?",
  "Describe your experience with monitoring and observability tools.",
  "How do you prioritize technical improvements versus new features?",
  "What's your approach to building resilient and fault-tolerant systems?",
]

export function getRandomQuestions(count = 10): string[] {
  const shuffled = [...questionBank].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count)
}
